/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package report;

import Class.DBO;
import java.io.File;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Aditya
 */
public class FrmLaporan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmLaporan
     */
    private String _fileName;
    private HashMap _parameter;
    private net.sf.jasperreports.swing.JRViewer pracetak;
   
    ttrs_penjualan._Entry e = new ttrs_penjualan._Entry();
    
   
    public FrmLaporan() {
        initComponents();
        
    
    }
    
    public void frm_public_initC(){
        initComponents();
    }
    
    private void FrmLaporan(String fileName) {
        DBO _cnn = new DBO();
        _cnn.makeConnect();
        _fileName = fileName;
        try {
            _fileName = _cnn.almtDir + _fileName;
            _parameter = new HashMap();
            File lp = new File(_fileName);
            JasperReport jr = (JasperReport)JRLoader.loadObject(lp);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, DBO.getConnection());
            pracetak = new net.sf.jasperreports.swing.JRViewer(jp);
            pracetak.setOpaque(true);
            pracetak.setVisible(true);
            setVisible(true);
            System.out.println("TERPANGGIL");
            jScrollPane1.add(pracetak);
            jScrollPane1.setViewportView(pracetak);
            this.setLocation(0, 0);
            this.setMaximum(true);
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
    
    public void FrmLaporan(String fileName, String faktur) {
        DBO _cnn = new DBO();
        _cnn.makeConnect();
        _fileName = fileName;
        e._faktur = faktur;
        
        try {
            _fileName = _cnn.almtDir + _fileName;
            String path="src/report/new_laporan_detail_groupby_faktur.jasper";
            _parameter = new HashMap();
            _parameter.put("faktur",e._faktur);
            File lp = new File(_fileName);
            JasperReport jr = (JasperReport)JRLoader.loadObject(lp);
            JasperPrint jp = JasperFillManager.fillReport(_fileName, _parameter, DBO.getConnection());
            pracetak = new net.sf.jasperreports.swing.JRViewer(jp);
            pracetak.setOpaque(true);
            pracetak.setVisible(true);
            setVisible(true);
            System.out.println("TERPANGGIL");
            jScrollPane1.add(pracetak);
            jScrollPane1.setViewportView(pracetak);
            this.setLocation(0, 0);
            this.setMaximum(true);
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void opsiCetak(){
        if (bTampil.getText().equals("Cetak Data Customer") == true) {
            FrmLaporan("report_customer.jasper");
        } else if(bTampil.getText().equals("Cetak Data User") == true) {
            FrmLaporan("report_user.jasper");
        } else if(bTampil.getText().equals("Cetak Data Product") == true) {
            FrmLaporan("report_product.jasper");
        } else if(bTampil.getText().equals("Cetak Data Transaksi Penjualan") == true) {
            FrmLaporan("new_report_ttrs_penjualan2.jasper");
        } else if(bTampil.getText().equals("Cetak Data Transaksi Penjualan Detail") == true) {
            FrmLaporan("report_transaksi_penjualan_detail.jasper");
        } else if(bTampil.getText().equals("Cetak Struk") == true) {
             FrmLaporan("new_laporan_detail_groupby_faktur.jasper", e._faktur);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bTampil = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        bTampil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_document-print_38984.png"))); // NOI18N
        bTampil.setText("Tampilkan");
        bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTampilActionPerformed(evt);
            }
        });

        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_40_Close_Switch_Off_Power_Switcher_Button_2142692.png"))); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bTampil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(bTampil)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTampilActionPerformed
        opsiCetak();
    }//GEN-LAST:event_bTampilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton bKeluar;
    public javax.swing.JButton bTampil;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
