/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mstr_user;

import Class.DBO;
import Class.mstr_user;
import java.awt.Dimension;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class _List extends javax.swing.JInternalFrame {

    private boolean append;
    private DefaultTableModel _tempttrs_mstr_customer;
    Connection _Cnn;
    String _User;
    
    public _List() {
        initComponents();
        
        String[] kolomtbl = {"USER ID", "NAMA", "JENIS KELAMIN", "TEMPAT LAHIR", "TGL LAHIR", "ALAMAT" , "KODE"};
        _tempttrs_mstr_customer = new DefaultTableModel(null, kolomtbl){
            Class[] types = new Class[] {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
            };
            
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            public boolean isCellEditable(int row, int col) {
                int kol = _tempttrs_mstr_customer.getColumnCount();
                return (col < kol) ? false : true;
            }
        };
        tbl_mstr_user.setModel(_tempttrs_mstr_customer);
        loadData();
    }
    public void hapusRowData() {
        int row = _tempttrs_mstr_customer.getColumnCount();
        
       while (_tempttrs_mstr_customer.getRowCount() > 0 ) {
           _tempttrs_mstr_customer.setRowCount(0);
       }
        
    }
    
    private void loadData(){
        String _sql = "";
        DBO vcon = new DBO();
        vcon.makeConnect();
        hapusRowData();
        try {
            _Cnn = vcon.vkoneksi;
            if(txtcari.getText().equals("")) {
                _sql = ""
                        + "SELECT user_id, nama,jenis_kelamin,tempat_lahir,tanggal_lahir,alamat,password "
                        + "FROM mstr_user";
                        
            } else {
                _sql = ""
                        + "SELECT * FROM mstr_user "
                        + "WHERE user_id LIKE '%" +txtcari.getText() + "%'"
                        + "OR nama LIKE '%" +txtcari.getText() + "%'"
                        + "OR alamat LIKE '%" +txtcari.getText() + "%'";
            }
            System.out.println(_sql);
            Statement st = _Cnn.createStatement();
            ResultSet rs = st.executeQuery(_sql);
            while ( rs.next()) {
                String user_id = rs.getString(1);
                String nama = rs.getString(2);
                String jenis_kelamin = rs.getString(3);
                String tempat_lahir = rs.getString(4);
                String tanggal_lahir = rs.getString(5);
                String alamat = rs.getString(6);
                String password = rs.getString(7);
                Object[] data = { user_id, nama, jenis_kelamin, tempat_lahir, tanggal_lahir, alamat, password
                                };
                _tempttrs_mstr_customer.addRow(data);
            }
            tbl_mstr_user.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_mstr_user.getColumnModel().getColumn(1).setPreferredWidth(10);
            tbl_mstr_user.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbl_mstr_user.getColumnModel().getColumn(3).setPreferredWidth(100);
            tbl_mstr_user.getColumnModel().getColumn(4).setPreferredWidth(100);
            tbl_mstr_user.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbl_mstr_user.getColumnModel().getColumn(6).setPreferredWidth(100);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERror" + e);
        }
    }
    ActionListener actionlist;
    private javax.swing.Timer timer = new javax.swing.Timer(100, actionlist);

    public void refresh() {
        try {
            loadData();
            ActionListener acl = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    timer.stop();
                }
            };
            timer = new javax.swing.Timer(100, acl);
            timer.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bRefresh = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mstr_user = new javax.swing.JTable();

        setTitle("Form List Data User");

        jXTitledPanel1.setTitle("List Data User");

        jLabel1.setText("Pencarian");

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariKeyTyped(evt);
            }
        });

        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_pencil-01_374624.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_list-add_118777.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_basket_1814090.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        bRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_view-refresh_118801.png"))); // NOI18N
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_40_Close_Switch_Off_Power_Switcher_Button_2142692.png"))); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });

        tbl_mstr_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_mstr_user);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bUbah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(444, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)))
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                        .addComponent(bUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus)
                        .addGap(15, 15, 15)
                        .addComponent(bRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bKeluar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        try {
            String kode = tbl_mstr_user.getValueAt(tbl_mstr_user.getSelectedRow(), 0).toString();
            _Entry f = new _Entry("", kode, "Edit");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width) /2, (parentSize.height)/2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.b_keluar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    loadData();
                }
            });
            f.b_simpan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    refresh();
                }
            });
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        try {
            _Entry f = new _Entry("", "", "Add");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width) /2, (parentSize.height)/2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.b_keluar.addActionListener( new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    refresh();
                }
            });
            f.b_simpan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    loadData();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String kode = tbl_mstr_user.getValueAt(tbl_mstr_user.getSelectedRow(), 0).toString();
        int pilih = JOptionPane.showConfirmDialog(this, "Hapus data user : "+kode,"KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION)  {
            mstr_user x = new mstr_user();
            x.hapusData(kode);
            refresh();
            loadData();
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        try {
            refresh();
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void txtcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyTyped
        try {
            loadData();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }//GEN-LAST:event_txtcariKeyTyped

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        try {
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        try {
            loadData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtcariKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JTable tbl_mstr_user;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
