/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mstr_product;

import mstr_product.*;
import Class.DBO;
import Class.mstr_product;
import java.awt.Dimension;
import java.sql.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class _List extends javax.swing.JInternalFrame {

    
    private boolean append;
    private DefaultTableModel _tempttrs_mstr_customer;
    Connection _Cnn;
    String _User;
    /**
     * Creates new form _List
     */
    public _List() {
        initComponents();
        
        String[] kolomtbl = {"PRODUCT ID","NAMA","SATUAN","HARGA"};
        _tempttrs_mstr_customer = new DefaultTableModel(null,kolomtbl) {
            Class[] types = new Class[]{
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class,
                java.lang.String.class
            };
            
            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            
            public boolean isCellEditable(int row, int col) {
                int kol = _tempttrs_mstr_customer.getColumnCount();
                return (col < kol) ? false : true;
            }
        };
        tbl_mstr_customer.setModel(_tempttrs_mstr_customer);
        muatData();
    }
    
    public void hapusRowData(){
        int row = _tempttrs_mstr_customer.getColumnCount();
        
        
        while (_tempttrs_mstr_customer.getRowCount() > 0) {
            _tempttrs_mstr_customer.setRowCount(0);
        }
    }
    
    private void muatData() {
        String _sql = "";
        DBO vcon = new DBO();
        vcon.makeConnect();
        hapusRowData();
        try {
            _Cnn = vcon.vkoneksi;
            if(txtcari.getText().equals("")){
                _sql = "SELECT prd_id,nama,satuan,harga FROM mstr_product";
            } else {
                _sql = "SELECT * FROM mstr_product WHERE"
                        + " prd_id LIKE '%"+txtcari.getText()+"%' OR"
                        + " nama LIKE '%"+txtcari.getText()+"%' OR"
                        + " satuan LIKE '%"+txtcari.getText()+"%' OR"
                        + " harga LIKE '%"+txtcari.getText()+"%'";
            }
            System.out.println(_sql);
            Statement st = _Cnn.createStatement();
            ResultSet rst = st.executeQuery(_sql);
            while (rst.next()) {
                String cust_id = rst.getString(1);
                String nama = rst.getString(2);
                String satuan = rst.getString(3);
                String harga = rst.getString(4);
                Object[] data = {cust_id,nama,satuan,harga};
                _tempttrs_mstr_customer.addRow(data);
                
            }
            tbl_mstr_customer.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbl_mstr_customer.getColumnModel().getColumn(1).setPreferredWidth(210);
            tbl_mstr_customer.getColumnModel().getColumn(3).setPreferredWidth(100);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" +e);
        }
    }
    
    ActionListener actionlist;
    private javax.swing.Timer timer = new javax.swing.Timer(10, actionlist);
    
    public void refresh(){
        try {
            muatData();
            ActionListener acl = new ActionListener() {
                public void actionPerformed(ActionEvent ae) {
                    timer.stop();
                }
            };
            timer = new javax.swing.Timer(10,acl);
            timer.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mstr_customer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        bUbah = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bRef = new javax.swing.JButton();
        bKeluar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jXTitledPanel1.setTitle("List Data Product");
        jXTitledPanel1.getContentContainer().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_mstr_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_mstr_customer);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 59, 550, 443));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pencarian");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        txtcari.setBackground(new java.awt.Color(0, 51, 102));
        txtcari.setForeground(new java.awt.Color(255, 255, 255));
        txtcari.setBorder(null);
        txtcari.setCaretColor(new java.awt.Color(255, 255, 255));
        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcariKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcariKeyTyped(evt);
            }
        });
        jPanel1.add(txtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, -1));

        bUbah.setBackground(new java.awt.Color(255, 255, 255));
        bUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_pencil-01_374624.png"))); // NOI18N
        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });
        jPanel1.add(bUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 59, 89, -1));

        bTambah.setBackground(new java.awt.Color(255, 255, 255));
        bTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_list-add_118777.png"))); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });
        jPanel1.add(bTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 100, 90, -1));

        bHapus.setBackground(new java.awt.Color(255, 0, 51));
        bHapus.setForeground(new java.awt.Color(255, 255, 255));
        bHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_basket_1814090.png"))); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        jPanel1.add(bHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 141, 89, -1));

        bRef.setBackground(new java.awt.Color(102, 255, 0));
        bRef.setForeground(new java.awt.Color(255, 255, 255));
        bRef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_view-refresh_118801.png"))); // NOI18N
        bRef.setText("Refresh");
        bRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefActionPerformed(evt);
            }
        });
        jPanel1.add(bRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 182, -1, -1));

        bKeluar.setBackground(new java.awt.Color(255, 0, 51));
        bKeluar.setForeground(new java.awt.Color(255, 255, 255));
        bKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_40_Close_Switch_Off_Power_Switcher_Button_2142692.png"))); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 223, 89, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 38, 156, 10));

        jXTitledPanel1.getContentContainer().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        try {
            _Entry f = new _Entry("","","Add");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width)/2, (parentSize.height)/2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.b_keluar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                   refresh(); 
                }
            });
            f.b_simpan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    refresh();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_bTambahActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        String kode = tbl_mstr_customer.getValueAt(tbl_mstr_customer.getSelectedRow(), 0).toString();
        int pilih = JOptionPane.showConfirmDialog(this,"Hapus data user :"+kode, "KONFIRMASI", JOptionPane.YES_NO_OPTION);
        if (pilih == JOptionPane.YES_OPTION){
            mstr_product x = new mstr_product();
            x.hapusData(kode);
            refresh();
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
        try {
            String kode = tbl_mstr_customer.getValueAt(tbl_mstr_customer.getSelectedRow(), 0).toString();
            _Entry f = new _Entry("",kode,"Edit");
            Dimension parentSize = this.getSize();
            f.setLocation((parentSize.width)/2,(parentSize.height)/2);
            f.setLocationRelativeTo(null);
            f.setVisible(true);
            f.b_keluar.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                   refresh();
               }
            });
            f.b_simpan.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    refresh();
                }
            });
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }//GEN-LAST:event_bUbahActionPerformed

    private void txtcariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyTyped
        try {
            refresh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_txtcariKeyTyped

    private void txtcariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyReleased
        try {
            refresh();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } 
    }//GEN-LAST:event_txtcariKeyReleased

    private void bRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefActionPerformed
        try {
            refresh();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_bRefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bKeluar;
    private javax.swing.JButton bRef;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JTable tbl_mstr_customer;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
