/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import Class.DBO;
import java.awt.*;
import javax.swing.*;
import report.FrmLaporan;

public class frmMenuUtama extends javax.swing.JFrame {
    
    private boolean append;
    Dimension parentSize = this.getSize();
    /**
     * Creates new form frmMenuUtama
     */
    public frmMenuUtama() {
        initComponents();
        settingKoneksi();
        setSize(java.awt.Toolkit.getDefaultToolkit().getScreenSize());
    }
    
    private void settingKoneksi() {
        DBO setting = new DBO();
        setting.makeConnect();
        if (setting.isConnected() == true ) {
            JOptionPane.showMessageDialog(null, "Terhubung dengan database");
        } else {
            JOptionPane.showMessageDialog(null, "Koneksi database gagal");
        }
    }
    
    private void linkUser() {
        mstr_user._List fus = new mstr_user._List();
        fus = new mstr_user._List();
        jDesktopPane1.add(fus);
        parentSize = this.getSize();
        Dimension childSize = fus.getSize();
        fus.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fus.setVisible(true);
    }
    
    private void linkCust() {
        mstr_customer._List fu = new mstr_customer._List();
        fu = new mstr_customer._List();
        jDesktopPane1.add(fu);
        parentSize = this.getSize();
        Dimension childSize = fu.getSize();
        fu.setLocation((parentSize.width - childSize.width) / 2, (parentSize.height - childSize.height) / 2);
        fu.setVisible(true);
    }
    
    private void linkProduct() {
        mstr_product._List fp = new mstr_product._List();
        fp = new mstr_product._List();
        jDesktopPane1.add(fp);
        parentSize = this.getSize();
        Dimension childSize = fp.getSize();
        fp.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        fp.setVisible(true);
    }

    private void linkPenjualan() {
        ttrs_penjualan._List ftp = new ttrs_penjualan._List();
        ftp = new ttrs_penjualan._List();
        jDesktopPane1.add(ftp);
        parentSize = this.getSize();
        Dimension childSize = ftp.getSize();
        ftp.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        ftp.setVisible(true);
    }
    
    private void linkFormCustomer() {
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        l.setVisible(true);
        l.bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.bTampil.setText("Cetak Data Customer");
            }
        });
    }
    
    private void linkFormUser() {
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width - childSize.width)/2, (parentSize.height - childSize.height)/2);
        l.setVisible(true);
        l.bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.bTampil.setText("Cetak Data User");
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        kontrol = new javax.swing.JMenu();
        su_login = new javax.swing.JMenuItem();
        su_logout = new javax.swing.JMenuItem();
        su_keluar = new javax.swing.JMenuItem();
        master = new javax.swing.JMenu();
        m_user = new javax.swing.JMenuItem();
        m_customer = new javax.swing.JMenuItem();
        m_product = new javax.swing.JMenuItem();
        ttrs = new javax.swing.JMenu();
        ttrs_penjualan = new javax.swing.JMenuItem();
        lap = new javax.swing.JMenu();
        l_user = new javax.swing.JMenuItem();
        l_cust = new javax.swing.JMenuItem();
        l_product = new javax.swing.JMenuItem();
        l_transaksi_penjualan = new javax.swing.JMenuItem();
        l_transaksi_penjualan_detail = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        kontrol.setText("Switch User");

        su_login.setText("login");
        su_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_loginActionPerformed(evt);
            }
        });
        kontrol.add(su_login);

        su_logout.setText("logout");
        su_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_logoutActionPerformed(evt);
            }
        });
        kontrol.add(su_logout);

        su_keluar.setText("keluar");
        su_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                su_keluarActionPerformed(evt);
            }
        });
        kontrol.add(su_keluar);

        jMenuBar2.add(kontrol);

        master.setText("Master");

        m_user.setText("Master User");
        m_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_userActionPerformed(evt);
            }
        });
        master.add(m_user);

        m_customer.setText("Master Customer");
        m_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_customerActionPerformed(evt);
            }
        });
        master.add(m_customer);

        m_product.setText("Master Product");
        m_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_productActionPerformed(evt);
            }
        });
        master.add(m_product);

        jMenuBar2.add(master);

        ttrs.setText("Transaksi");

        ttrs_penjualan.setText("Transaksi Penjualan");
        ttrs_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttrs_penjualanActionPerformed(evt);
            }
        });
        ttrs.add(ttrs_penjualan);

        jMenuBar2.add(ttrs);

        lap.setText("Laporan");

        l_user.setText("Laporan User");
        l_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_userActionPerformed(evt);
            }
        });
        lap.add(l_user);

        l_cust.setText("Laporan Customer");
        l_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_custActionPerformed(evt);
            }
        });
        lap.add(l_cust);

        l_product.setText("Laporan Product");
        l_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_productActionPerformed(evt);
            }
        });
        lap.add(l_product);

        l_transaksi_penjualan.setText("Laporan Transaksi Penjualan");
        l_transaksi_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_transaksi_penjualanActionPerformed(evt);
            }
        });
        lap.add(l_transaksi_penjualan);

        l_transaksi_penjualan_detail.setText("Laporan Detail Transaksi Penjualan");
        l_transaksi_penjualan_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_transaksi_penjualan_detailActionPerformed(evt);
            }
        });
        lap.add(l_transaksi_penjualan_detail);

        jMenuBar2.add(lap);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void su_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_loginActionPerformed
        FormLogin fl = new FormLogin();
        parentSize = this.getSize();
        Dimension childSize = fl.getSize();
        fl.setLocation((parentSize.width - childSize.width) /2 , (parentSize.height - childSize.height) / 2);
        fl.setVisible(true);
    }//GEN-LAST:event_su_loginActionPerformed

    private void su_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_logoutActionPerformed
        append = false;
        this.setVisible(append);
        new FormLogin().setVisible(true);
    }//GEN-LAST:event_su_logoutActionPerformed

    private void su_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_su_keluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_su_keluarActionPerformed

    private void m_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_userActionPerformed
        linkUser();
    }//GEN-LAST:event_m_userActionPerformed

    private void m_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_customerActionPerformed
        linkCust();
    }//GEN-LAST:event_m_customerActionPerformed

    private void m_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_productActionPerformed
        linkProduct();
    }//GEN-LAST:event_m_productActionPerformed

    private void l_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_userActionPerformed
        linkFormUser();
    }//GEN-LAST:event_l_userActionPerformed

    private void l_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_custActionPerformed
        linkFormCustomer();
    }//GEN-LAST:event_l_custActionPerformed

    private void ttrs_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttrs_penjualanActionPerformed
        linkPenjualan();
    }//GEN-LAST:event_ttrs_penjualanActionPerformed

    private void l_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_productActionPerformed
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        l.setVisible(true);
        l.bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.bTampil.setText("Cetak Data Product");
            }
        });
    }//GEN-LAST:event_l_productActionPerformed

    private void l_transaksi_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_transaksi_penjualanActionPerformed
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        l.setVisible(true);
        l.bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.bTampil.setText("Cetak Data Transaksi Penjualan");
            }
        });
    }//GEN-LAST:event_l_transaksi_penjualanActionPerformed

    private void l_transaksi_penjualan_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_transaksi_penjualan_detailActionPerformed
        FrmLaporan l = new FrmLaporan();
        jDesktopPane1.add(l);
        parentSize = this.getSize();
        Dimension childSize = l.getSize();
        l.setLocation((parentSize.width - childSize.width) /2 ,(parentSize.height - childSize.height) /2);
        l.setVisible(true);
        l.bTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l.bTampil.setText("Cetak Data Transaksi Penjualan Detail");
            }
        });
    }//GEN-LAST:event_l_transaksi_penjualan_detailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu kontrol;
    private javax.swing.JMenuItem l_cust;
    private javax.swing.JMenuItem l_product;
    private javax.swing.JMenuItem l_transaksi_penjualan;
    private javax.swing.JMenuItem l_transaksi_penjualan_detail;
    private javax.swing.JMenuItem l_user;
    private javax.swing.JMenu lap;
    private javax.swing.JMenuItem m_customer;
    private javax.swing.JMenuItem m_product;
    private javax.swing.JMenuItem m_user;
    private javax.swing.JMenu master;
    private javax.swing.JMenuItem su_keluar;
    private javax.swing.JMenuItem su_login;
    private javax.swing.JMenuItem su_logout;
    private javax.swing.JMenu ttrs;
    private javax.swing.JMenuItem ttrs_penjualan;
    // End of variables declaration//GEN-END:variables
}
